- name: Post-Install | Disable mailbox
  when:
  - mqueue_stat.exists | lower == 'true'
  - mqueue_stat.islnk | lower == 'false'
  block:
  - name: Post-Install | Remove mqueue directory
    file: path={{ mqueue_stat.path }} state=absent

  - name: Post-Install | Create mqueue symlink
    file: path={{ mqueue_stat.path }} src=/dev/null state=link

- name: Post-Install | Set tmpfs paths
  with_items: '{{ bsd_read_only_tmpfs_mountpoints }}'
  notify: reboot
  mount:
    path: '{{ item.path }}'
    src: tmpfs
    fstype: tmpfs
    opts: '{{ item.opts }}'
    state: present

- name: Post-Install | Configure dhclient
  notify: reboot
  template:
    src: dhclient.j2
    dest: /etc/rc.conf.d/dhclient
    owner: root
    mode: 0644

- name: Post-Install | Set rootfs read only
  notify: reboot
  mount:
    path: /
    src: /dev/ufs/rootfs
    fstype: ufs
    opts: ro
    state: present

- name: Post-Install | Move pkg db
  when: pkg_db.stat.exists is false
  command: mv /var/db/pkg /mnt

- name: Post-Install | Set pkg db dir to /mnt/pkg
  lineinfile:
    path: /usr/local/etc/pkg.conf
    state: present
    regexp: '#PKG_DBDIR ='
    line: PKG_DBDIR = "/mnt/pkg";

- name: Post-Install | Purge pkg cache (1/2)
  register: files_to_delete
  find:
    paths: /var/cache/pkg
    patterns: '*.pkg'

- name: Post-Install | Purge pkg cache (2/2)
  with_items: '{{ files_to_delete.files }}'
  file:
    path: '{{ item.path }}'
    state: absent

